// floor-fleet.mjs — shared row-building for Intake (floor-tagged) and Maintain
// (fleet-tagged): both are views of the SAME measurement (eval/yardstick.yaml),
// filtered to a tag population. Neither reads findings directly — only the
// yardstick's measurement plus the register (title/check/tier/topic) and the
// run manifest (what was not seen). Ordering: tier order, then register order.
import { loadRegistry, loadMeasurement } from '../yardstick/measure.mjs';
import { loadManifest, loadAdapters, dispositions } from '../map/project.mjs';

// decided_by: the instrument name from the row's decide, or "owner" for claim
// rows; a census/facet row is decided by that mechanism's own name.
export function decidedBy(d) {
  if (d.decide.kind === 'instrument') return d.decide.scanner;
  if (d.decide.kind === 'claim') return 'owner';
  return d.decide.kind;
}

// Build the three lists + not_seen for one tag population (floor or fleet).
// withFloor: also stamp `floor: true|false` on every row (Maintain's population
// is fleet-tagged but still needs to say which of those are ALSO floor rows).
// Returns null when the run has no yardstick measurement yet.
export function buildRows(runDir, tag, { withFloor = false } = {}) {
  const reg = loadRegistry();
  const measurement = loadMeasurement(runDir);
  if (!measurement) return null;
  const byId = new Map(measurement.map((r) => [r.id, r]));
  const tierRank = Object.fromEntries((reg.tiers || []).map((t, i) => [t, i]));

  const population = reg.descriptors
    .map((d, i) => ({ d, i }))
    .filter(({ d }) => (d.tags || []).includes(tag))
    .sort((a, b) => (tierRank[a.d.tier] ?? 999) - (tierRank[b.d.tier] ?? 999) || a.i - b.i)
    .map(({ d }) => d);

  const open = [], met = [], to_run = [];
  for (const d of population) {
    const m = byId.get(d.id) || { status: 'not-measured', findings: [], note: 'not measured — the run carries no yardstick row for this requirement' };
    const base = { id: d.id, tier: d.tier, topic: d.topic, title: d.title };
    if (withFloor) base.floor = (d.tags || []).includes('floor');
    if (m.status === 'met') {
      met.push({ ...base, note: m.note });
    } else if (m.status === 'not-measured') {
      to_run.push({ ...base, check: d.check, decided_by: decidedBy(d), note: m.note });
    } else { // unmet | mixed
      open.push({ ...base, status: m.status, met: m.met, of: m.of, findings: m.findings || [], note: m.note, check: d.check });
    }
  }

  const manifest = loadManifest(runDir);
  const adapters = loadAdapters();
  const dispo = dispositions(manifest, adapters);
  const not_seen = [
    ...dispo.skipped.map((s) => ({ scanner: s.id, status: 'skipped', reason: s.reason })),
    ...dispo.failed.map((s) => ({ scanner: s.id, status: 'failed', reason: s.reason })),
    ...dispo.missing.map((id) => ({ scanner: id, status: 'missing', reason: 'no disposition recorded in the run manifest' })),
  ];

  return { population, open, met, to_run, not_seen };
}

// ── shared YAML emission (yaml-min's constrained block-only subset) ──────────
const q = (s) => `"${String(s == null ? '' : s).replace(/"/g, '\\"')}"`;
function openRowYaml(r) {
  const L = [`  - id: ${r.id}`, `    tier: ${r.tier}`, `    topic: ${r.topic}`];
  if (r.floor !== undefined) L.push(`    floor: ${r.floor}`);
  L.push(`    title: ${q(r.title)}`, `    status: ${r.status}`);
  if (r.of != null) L.push(`    met: ${r.met}`, `    of: ${r.of}`);
  L.push(`    findings: [${(r.findings || []).join(', ')}]`, `    note: ${q(r.note)}`, `    check: ${q(r.check)}`);
  return L.join('\n');
}
function metRowYaml(r) {
  const L = [`  - id: ${r.id}`, `    tier: ${r.tier}`, `    topic: ${r.topic}`];
  if (r.floor !== undefined) L.push(`    floor: ${r.floor}`);
  L.push(`    title: ${q(r.title)}`, `    note: ${q(r.note)}`);
  return L.join('\n');
}
function toRunRowYaml(r) {
  const L = [`  - id: ${r.id}`, `    tier: ${r.tier}`, `    topic: ${r.topic}`];
  if (r.floor !== undefined) L.push(`    floor: ${r.floor}`);
  L.push(`    title: ${q(r.title)}`, `    check: ${q(r.check)}`, `    decided_by: ${r.decided_by}`, `    note: ${q(r.note)}`);
  return L.join('\n');
}
function notSeenRowYaml(r) {
  return [`  - scanner: ${r.scanner}`, `    status: ${r.status}`, `    reason: ${q(r.reason)}`].join('\n');
}

// Renders the full data file for a view (Intake or Maintain): view name,
// run, the yardstick's version, counts, then the four lists.
export function toYaml(view, runName, yardstickVersion, built) {
  const { population, open, met, to_run, not_seen } = built;
  const L = [`# ${view}.yaml — GENERATED by views/${view}.mjs. Do not hand-edit.`, `view: ${view}`, `run: ${runName}`, `yardstick: ${yardstickVersion}`];
  L.push('counts:', `  requirements: ${population.length}`, `  open: ${open.length}`, `  met: ${met.length}`, `  to_run: ${to_run.length}`);
  L.push('open:'); for (const r of open) L.push(openRowYaml(r));
  L.push('met:'); for (const r of met) L.push(metRowYaml(r));
  L.push('to_run:'); for (const r of to_run) L.push(toRunRowYaml(r));
  L.push('not_seen:'); for (const r of not_seen) L.push(notSeenRowYaml(r));
  return L.join('\n') + '\n';
}
