#!/usr/bin/env node
// since.mjs — Since: what changed between this run and a previous one, so a
// stewarded repository's own scheduled runs say what moved without a person
// diffing two packages by hand (views/README.md "Since: what changed?"). Reads ONLY the two runs' yardstick.yaml (via yardstick/compare.mjs)
// for the requirement-level story, plus the two runs' findings for the
// finding-level story — never recomputes a status itself (views/README.md: a
// view decides no requirement on its own).
//
// Writes views/since.yaml (data) + SINCE.md (plain, neutral — counts only in the
// headline, no verdict, no severity the views do not already compute: CLAUDE.md
// rule 1) at the run root.
//
// Usage: node assay.mjs since <run-dir> --previous <prev-run-dir> [--confidential]
import { writeFileSync, existsSync, readFileSync, mkdirSync } from 'node:fs';
import { basename, dirname } from 'node:path';
import { isMain } from '../map/doctrine.mjs';
import { parseYaml } from '../lib/yaml-min.mjs';
import { loadFindings } from '../map/project.mjs';
import { loadYardstick } from '../yardstick/measure.mjs';
import { loadYardstickDoc } from '../yardstick/ratchet.mjs';
import { compare, compareFindings } from '../yardstick/compare.mjs';
import { viewPath, sincePagePath, prosePath as runProsePath } from '../lib/run-layout.mjs';

// buildSince(previousDoc, currentDoc, reg) — pure over two { version, requirements }
// documents plus the loaded register (for title/tier/topic, tier-ordered — the same
// ordering every other view uses). Requirement rows in tier order; the yardstick-only
// list (the yardstick itself changed) kept separate, in id order.
export function buildSince(previousDoc, currentDoc, reg) {
  const { rows, previousVersion, currentVersion, versionChanged } = compare(previousDoc, currentDoc);
  const byId = new Map(rows.map((r) => [r.id, r]));
  const tierRank = Object.fromEntries((reg.tiers || []).map((t, i) => [t, i]));
  const ordered = reg.requirements.slice().sort((a, b) => (tierRank[a.tier] ?? 999) - (tierRank[b.tier] ?? 999));
  const regressed = [], improved = [], newly_measured = [], no_longer_measured = [];
  for (const d of ordered) {
    const r = byId.get(d.id);
    if (!r || r.classification === 'yardstick-only') continue; // reported separately below
    const base = { id: d.id, tier: d.tier, topic: d.topic, title: d.title, previous: r.previous, current: r.current, note: (r.current && r.current.note) ?? (r.previous && r.previous.note) ?? '' };
    if (r.classification === 'regressed') regressed.push(base);
    else if (r.classification === 'improved') improved.push(base);
    else if (r.classification === 'newly-measured') newly_measured.push(base);
    else if (r.classification === 'no-longer-measured') no_longer_measured.push(base);
  }
  const yardstick_only = rows.filter((r) => r.classification === 'yardstick-only').map((r) => {
    const d = reg.requirements.find((x) => x.id === r.id);
    const side = r.side === 'previous' ? r.previous : r.current;
    return { id: r.id, side: r.side, title: (d && d.title) || r.id, status: side.status, basis: side.basis };
  });
  return { previousVersion, currentVersion, versionChanged, regressed, improved, newly_measured, no_longer_measured, yardstick_only };
}

// ── YAML emission (yaml-min's block-only subset: no inline flow maps) ───────
const q = (s) => `"${String(s == null ? '' : s).replace(/"/g, '\\"')}"`;
function statusBlock(indent, label, s) {
  const L = [`${indent}${label}:`, `${indent}  status: ${s.status}`, `${indent}  basis: ${s.basis || 'run'}`];
  if (s.findings) L.push(`${indent}  findings: [${(s.findings || []).join(', ')}]`);
  return L;
}
function reqRowYaml(r) {
  const L = [`  - id: ${r.id}`, `    tier: ${r.tier}`, `    topic: ${r.topic}`, `    title: ${q(r.title)}`];
  L.push(...statusBlock('    ', 'previous', r.previous));
  L.push(...statusBlock('    ', 'current', r.current));
  L.push(`    note: ${q(r.note)}`);
  return L.join('\n');
}
function yardstickOnlyRowYaml(r) {
  return [`  - id: ${r.id}`, `    side: ${r.side}`, `    title: ${q(r.title)}`, `    status: ${r.status}`, `    basis: ${r.basis || 'run'}`].join('\n');
}
function findingRowYaml(f) {
  return [`    - fingerprint: ${q(f.fingerprint)}`, `      id: ${f.id}`, `      source: ${f.source}`,
    `      dimension: ${q(f.dimension || '')}`, `      native_category: ${q(f.native_category || '')}`,
    `      evidence: [${(f.evidence || []).join(', ')}]`, `      observation: ${q(f.observation)}`].join('\n');
}

export function toYaml(runId, previousId, since, findingsDelta) {
  const L = ['# since.yaml — GENERATED by views/since.mjs. Do not hand-edit.',
    'view: since', `run: ${runId}`, `previous: ${previousId}`,
    `yardstick: ${since.currentVersion}`, `previous_yardstick: ${since.previousVersion}`,
    `yardstick_version_changed: ${since.versionChanged}`, 'counts:',
    `  regressed: ${since.regressed.length}`, `  improved: ${since.improved.length}`,
    `  newly_measured: ${since.newly_measured.length}`, `  no_longer_measured: ${since.no_longer_measured.length}`,
    `  yardstick_only: ${since.yardstick_only.length}`,
    `  findings_new: ${findingsDelta.new.length}`, `  findings_no_longer_found: ${findingsDelta.no_longer_found.length}`];
  for (const [key, list] of [['regressed', since.regressed], ['improved', since.improved], ['newly_measured', since.newly_measured], ['no_longer_measured', since.no_longer_measured]]) {
    L.push(`${key}:`); for (const r of list) L.push(reqRowYaml(r));
  }
  L.push('yardstick_only:'); for (const r of since.yardstick_only) L.push(yardstickOnlyRowYaml(r));
  L.push('findings:', '  new:'); for (const f of findingsDelta.new) L.push(findingRowYaml(f));
  L.push('  no_longer_found:'); for (const f of findingsDelta.no_longer_found) L.push(findingRowYaml(f));
  return L.join('\n') + '\n';
}

// ── the plain page: most useful first (regressed, then improved, then the
// measured/not-measured transitions), findings last. Headline is counts only —
// no verdict, no severity the views do not already compute (CLAUDE.md rule 1).
export function renderMd(runId, previousId, since, findingsDelta, confidential = false) {
  const out = [];
  out.push('---', 'type: doc', ...(confidential ? ['confidential: true'] : []), `title: "Since ${previousId} — ${runId}"`, '---', '');
  out.push(`# Since ${previousId} — ${runId}`, '');
  out.push(`_What changed since the previous run. Counts only — no verdict, no severity the views do not`);
  out.push('already compute._', '');
  out.push(`**${since.regressed.length} regressed · ${since.improved.length} improved · ${since.newly_measured.length} newly measured · ${since.no_longer_measured.length} no longer measured · ${since.yardstick_only.length} yardstick-only · ${findingsDelta.new.length} findings new · ${findingsDelta.no_longer_found.length} findings no longer found**.`, '');
  if (since.versionChanged) out.push(`_The yardstick itself changed between runs: ${since.previousVersion} → ${since.currentVersion}. A requirement's id can carry a different meaning across that boundary._`, '');

  out.push('## Regressed', '');
  if (since.regressed.length) for (const r of since.regressed) out.push(`- **${r.id}** _(${r.tier}/${r.topic})_ — ${r.title}. ${r.previous.status} → ${r.current.status}${r.current.findings.length ? ` (${r.current.findings.join(', ')})` : ''}. ${r.note}`);
  else out.push('_Nothing regressed._');
  out.push('');

  out.push('## Improved', '');
  if (since.improved.length) for (const r of since.improved) out.push(`- **${r.id}** _(${r.tier}/${r.topic})_ — ${r.title}. ${r.previous.status} → ${r.current.status}. ${r.note}`);
  else out.push('_Nothing improved._');
  out.push('');

  out.push('## Newly measured', '');
  if (since.newly_measured.length) for (const r of since.newly_measured) out.push(`- **${r.id}** _(${r.tier}/${r.topic})_ — ${r.title}. not-measured → ${r.current.status}. ${r.note}`);
  else out.push('_Nothing newly measured._');
  out.push('');

  out.push('## No longer measured', '');
  if (since.no_longer_measured.length) for (const r of since.no_longer_measured) out.push(`- **${r.id}** _(${r.tier}/${r.topic})_ — ${r.title}. ${r.previous.status} → ${r.current.status}. ${r.note}`);
  else out.push('_Nothing dropped off the measured scale._');
  out.push('');

  if (since.yardstick_only.length) {
    out.push('## Yardstick changed', '');
    out.push('_A requirement present on only one side — the yardstick itself was edited between runs._', '');
    for (const r of since.yardstick_only) out.push(`- **${r.id}** _(${r.side} only)_ — ${r.title}: ${r.status}.`);
    out.push('');
  }

  out.push('## Findings new since the previous run', '');
  if (findingsDelta.new.length) for (const f of findingsDelta.new) out.push(`- **${f.id}** _(${f.source})_ — ${f.observation} — ${(f.evidence || []).join(', ')}`);
  else out.push('_None._');
  out.push('');

  out.push('## Findings no longer found', '');
  out.push('_Not matched in this run by fingerprint (yardstick/compare.mjs). "No longer found" — never "fixed":');
  out.push('absence of a finding is absence of re-detection, not proof the underlying fact is gone._', '');
  if (findingsDelta.no_longer_found.length) for (const f of findingsDelta.no_longer_found) out.push(`- **${f.id}** _(${f.source})_ — ${f.observation} — ${(f.evidence || []).join(', ')}`);
  else out.push('_None._');
  out.push('');

  out.push('---', `_assay evaluation engine. Run \`${runId}\`, since \`${previousId}\`._`);
  return out.join('\n') + '\n';
}

if (isMain(import.meta.url)) {
  const args = process.argv.slice(2);
  const prevIdx = args.indexOf('--previous');
  const previous = prevIdx > -1 ? args[prevIdx + 1] : null;
  const runDir = args.find((a, i) => !a.startsWith('--') && !(prevIdx > -1 && i === prevIdx + 1));
  if (!runDir || !previous) { console.error('usage: node assay.mjs since <run-dir> --previous <prev-run-dir> [--confidential]'); process.exit(2); }

  let currentDoc, previousDoc;
  try { currentDoc = loadYardstickDoc(runDir); }
  catch (e) { console.error(`✗ since: cannot read ${runDir}'s yardstick.yaml (${e.message})`); process.exit(2); }
  try { previousDoc = loadYardstickDoc(previous); }
  catch (e) { console.error(`✗ since: cannot read ${previous}'s yardstick.yaml (${e.message})`); process.exit(2); }

  let reg;
  try { reg = loadYardstick(); }
  catch (e) { console.error(`✗ since: cannot load the yardstick register (${e.message})`); process.exit(2); }

  const since = buildSince(previousDoc, currentDoc, reg);
  const findingsDelta = compareFindings(loadFindings(previous), loadFindings(runDir));

  const runId = basename(runDir), previousId = basename(previous);
  let proseConfidential = false;
  try { const pp = runProsePath(runDir); if (existsSync(pp)) proseConfidential = parseYaml(readFileSync(pp, 'utf8'))?.confidential === true; } catch {}
  const confidential = process.argv.includes('--confidential') || proseConfidential;

  const yamlOut = toYaml(runId, previousId, since, findingsDelta);
  const mdOut = renderMd(runId, previousId, since, findingsDelta, confidential);

  const yamlDst = viewPath(runDir, 'since');
  mkdirSync(dirname(yamlDst), { recursive: true });
  writeFileSync(yamlDst, yamlOut);
  writeFileSync(sincePagePath(runDir), mdOut);
  console.log(`wrote ${yamlDst} + ${sincePagePath(runDir)} (${since.regressed.length} regressed · ${since.improved.length} improved · ${findingsDelta.new.length} findings new · ${findingsDelta.no_longer_found.length} findings no longer found)`);
}
