// ── the feedback hook: backlog.mjs exercised, its authored half has a path and a schema (#57, F-520, F-522) ──
// backlog.mjs had no block of its own; the authored half (curated classes, the surprise
// notes) had no path in lib/run-layout.mjs, no schema and no validator check, and nothing
// read map/backlog.yaml back.
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { parseYaml } from '../../lib/yaml-min.mjs';
import { HERE, ROOT, negFailures, copyFixtureFindings, copyFixtureScanners } from '../harness.mjs';

export const label = 'backlog';

export async function run() {
  const fail = (m) => negFailures.push('backlog: ' + m);
  let D = null;
  try { D = await import('../../lib/run-data.mjs'); } catch { /* the run-data block reports it */ }
  const L = await import('../../lib/run-layout.mjs');
  if (typeof L.backlogAuthoredPath !== 'function') fail('lib/run-layout.mjs must place the authored half of the backlog');
  const src = readFileSync(join(ROOT, 'map', 'backlog.mjs'), 'utf8');
  const head = src.split('\nimport ')[0];
  for (const f of ['map/backlog.yaml', 'map/backlog-authored.yaml']) if (!head.includes(f)) fail(`backlog.mjs's header must name ${f}`);
  // the header names only files the run layout places or the repository has
  for (const m of head.matchAll(/\b((?:map|views|lib)\/[\w./-]+\.(?:mjs|yaml|md))\b/g)) {
    const p = m[1];
    const placed = ['map/backlog.yaml', 'map/backlog-authored.yaml', 'views/improve/maturity-grades.yaml'].includes(p);
    if (!placed && !existsSync(join(ROOT, p))) fail(`backlog.mjs's header names ${p}, which does not exist`);
  }
  const tmp = join(HERE, 'tmp-backlog'); rmSync(tmp, { recursive: true, force: true });
  const run = join(tmp, 'run'), prior = join(tmp, 'prior');
  for (const d of [run, prior]) { copyFixtureFindings('notesbox', d); copyFixtureScanners('notesbox', d); }
  // the prior judged one channel's telemetry differently: one descriptor-divergence item
  const dPath = join(prior, 'map', 'findings', 'repo-eval-delegation.yaml');
  const before = readFileSync(dPath, 'utf8');
  writeFileSync(dPath, before.replace('    telemetry: unstructured\n', '    telemetry: none\n'));
  if (readFileSync(dPath, 'utf8') === before) fail('test setup: the prior must change one telemetry descriptor');
  const w = spawnSync(process.execPath, [join(ROOT, 'map', 'backlog.mjs'), run, '--prior', prior, '--write'], { encoding: 'utf8' });
  if (w.status !== 0) fail(`backlog --prior --write must exit 0 (got ${w.status}: ${w.stderr})`);
  const out = L.backlogPath(run);
  if (!existsSync(out)) fail('backlog --write must write map/backlog.yaml');
  else {
    const txt = readFileSync(out, 'utf8');
    if (!/^# map\/backlog\.yaml — GENERATED by map\/backlog\.mjs/.test(txt)) fail('the written file must open naming itself and its writer');
    let doc = null; try { doc = parseYaml(txt); } catch (e) { fail(`map/backlog.yaml must parse (${e.message})`); }
    if (doc && D) { const e = D.checkBacklog(doc); if (e.length) fail(`the written backlog must pass its schema (got ${e.join('; ')})`); }
    const dd = (doc?.items || []).filter((i) => i.class === 'descriptor-divergence');
    if (dd.length !== 1 || !/telemetry/.test(dd[0].observation)) fail(`one descriptor-divergence item naming telemetry expected (got ${JSON.stringify(dd)})`);
    if (doc?.counts?.['un-enumerated-population'] !== null || !/no --target/.test(doc?.not_computed?.['un-enumerated-population'] || '')) fail('a class not requested must read not computed with its reason, never 0');
  }
  // validate reads the backlog back, the authored half included, and fails closed on a malformed one
  const val = () => spawnSync(process.execPath, [join(ROOT, 'map', 'validate.mjs'), run], { encoding: 'utf8' });
  const authored = L.backlogAuthoredPath ? L.backlogAuthoredPath(run) : join(run, 'map', 'backlog-authored.yaml');
  writeFileSync(authored, [
    '# map/backlog-authored.yaml — the authored half of the backlog (SCHEMA.md §5b)',
    'items:', '  - id: OB-A01', '    class: tooling-gap', '    status: proposed',
    '    observation: "enumerate matched no Node child_process call site."', '    evidence: ["map/enumerate.mjs:105"]',
    '    mechanism: "Teach the effect-site detector the Node shapes."',
    'notes:', '  - "A strength shape the dimensions did not anticipate."', '',
  ].join('\n'));
  const v1 = val();
  if (v1.status !== 0) fail(`validate must pass a well-formed backlog and authored half (stderr: ${String(v1.stderr).split('\n').slice(0, 4).join(' | ')})`);
  writeFileSync(authored, readFileSync(authored, 'utf8').replace('class: tooling-gap', 'class: vibes'));
  const v2 = val();
  if (v2.status === 0 || !/backlog-authored\.yaml/.test(v2.stderr) || !/vibes/.test(v2.stderr)) fail(`validate must fail closed on an authored item outside the closed classes, naming the file (got ${v2.status})`);
  writeFileSync(authored, 'items: []\nnotes: []\n');
  const v3 = val();
  if (v3.status === 0 || !/notes/.test(v3.stderr)) fail('validate must refuse an authored half with no note (one saying nothing surprised counts)');
  rmSync(authored);
  writeFileSync(out, readFileSync(out, 'utf8').replace(/class: descriptor-divergence/, 'class: made-up'));
  const v4 = val();
  if (v4.status === 0 || !/backlog\.yaml/.test(v4.stderr)) fail(`validate must fail closed on a computed backlog item outside the closed classes (got ${v4.status})`);
  rmSync(tmp, { recursive: true, force: true });
}
