#!/usr/bin/env node
// topics.mjs — the yardstick's measurement, grouped by TOPIC (the axis roster
// plus custody, reproducibility and operability, the tiers with no axis of their own).
// Feeds IMPROVE.md's "Requirements by topic" section (eval/improve.yaml) and
// the axis walk's per-axis requirement lists + the custody, reproducibility and operability
// sections. Reads ONLY the yardstick's measurement (eval/yardstick.yaml,
// falling back to the legacy eval/view-descriptors.yaml) plus the yardstick,
// for title/tier/topic — never findings directly.
//
// Usage: node views/improve/topics.mjs <run-dir> [--write]
//   --write   regenerate eval/improve.yaml (generated; never hand-edit)
import { writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { loadRegistry, loadMeasurement, TOPICS } from '../../yardstick/measure.mjs';
import { isMain } from '../../map/doctrine.mjs';

// Group every requirement by topic: { topic, met, unmet, mixed, not_measured,
// rows: [{id, title, status}] }. Every requirement lands in exactly one topic
// (its register row's own `topic:`); every topic in TOPICS appears, even with
// zero rows, so a topic with no requirements today still reads "not measured",
// never silently absent. Ordering within a topic: tier order, then register order.
export function buildTopics(measurementRows, reg) {
  const byId = new Map(measurementRows.map((r) => [r.id, r]));
  const tierRank = Object.fromEntries((reg.tiers || []).map((t, i) => [t, i]));
  const byTopic = new Map(TOPICS.map((t) => [t, { topic: t, met: 0, unmet: 0, mixed: 0, not_measured: 0, rows: [] }]));
  reg.requirements.forEach((d, i) => {
    const m = byId.get(d.id);
    const status = m ? m.status : 'not-measured';
    if (!byTopic.has(d.topic)) byTopic.set(d.topic, { topic: d.topic, met: 0, unmet: 0, mixed: 0, not_measured: 0, rows: [] });
    const g = byTopic.get(d.topic);
    const key = status === 'not-measured' ? 'not_measured' : status;
    g[key] = (g[key] || 0) + 1;
    g.rows.push({ id: d.id, title: d.title, status, _tier: tierRank[d.tier] ?? 999, _reg: i });
  });
  for (const g of byTopic.values()) g.rows.sort((a, b) => a._tier - b._tier || a._reg - b._reg);
  for (const g of byTopic.values()) for (const r of g.rows) { delete r._tier; delete r._reg; }
  return TOPICS.map((t) => byTopic.get(t));
}

const q = (s) => `"${String(s).replace(/"/g, '\\"')}"`;
export function toYaml(topics) {
  const L = ['# improve.yaml — GENERATED by views/improve/topics.mjs --write. Do not hand-edit.',
    "# Every requirement on the yardstick, grouped by topic (the axis roster plus custody,",
    '# reproducibility and operability), each exactly once. Fed by eval/yardstick.yaml + yardstick/requirements.yaml.',
    'topics:'];
  for (const t of topics) {
    L.push(`  - topic: ${t.topic}`, `    met: ${t.met}`, `    unmet: ${t.unmet}`, `    mixed: ${t.mixed}`, `    not_measured: ${t.not_measured}`);
    L.push('    rows:');
    for (const r of t.rows) L.push(`      - id: ${r.id}`, `        title: ${q(r.title)}`, `        status: ${r.status}`);
  }
  return L.join('\n') + '\n';
}

// Build directly from a run dir (used by the walk + the report; returns null
// when the run has no yardstick measurement yet — a raw, uncompiled base).
export function buildTopicsForRun(runDir) {
  const rows = loadMeasurement(runDir);
  if (!rows) return null;
  const reg = loadRegistry();
  return buildTopics(rows, reg);
}

if (isMain(import.meta.url)) {
  const args = process.argv.slice(2);
  const dir = args.find((a) => !a.startsWith('--'));
  if (!dir) { console.error('usage: node views/improve/topics.mjs <run-dir> [--write]'); process.exit(2); }
  const topics = buildTopicsForRun(dir);
  if (!topics) { console.error(`no yardstick measurement under ${dir} — run: node assay.mjs measure ${dir} --write`); process.exit(2); }
  for (const t of topics) console.log(`${t.topic.padEnd(20)} met ${t.met} · unmet ${t.unmet} · mixed ${t.mixed} · not measured ${t.not_measured}`);
  if (args.includes('--write')) {
    const evalDir = existsSync(join(dir, 'eval')) ? join(dir, 'eval') : dir;
    const out = join(evalDir, 'improve.yaml');
    writeFileSync(out, toYaml(topics));
    console.error(`wrote ${out}`);
  }
}
